FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# deps do scheduler
RUN pip install --no-cache-dir requests pyyaml

# copie do lugar certo (pasta agent do seu projeto) para /app no container
COPY agent/scheduler.py /app/scheduler.py

# (opcional) tzdata para respeitar TZ=America/Sao_Paulo
RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["python", "/app/scheduler.py"]
