- fluxo_name: extracao_zephyr_diaria
  horario: '14:34'
  data: 26/09/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"zephyr","testcases":2,"executions":0,"saved":["config/data/zephyr_testcases_20250926_173343.csv","config/data/zephyr_executions_20250926_173343.csv"],"latest":["config/data/zephyr_testcases_latest.csv","config/data/zephyr_executions_latest.csv"]}'
  endpoint: /run_zephyr/
  api_url: http://massai-api:8000
- fluxo_name: extracao_zephyr_diaria
  horario: '14:34'
  data: 02/10/2025
  status: Falha
  mensagem: '500 Server Error: Internal Server Error for url: http://massai-api:8000/run_zephyr/'
  endpoint: /run_zephyr/
  api_url: http://massai-api:8000
