- fluxo_name: Fluxo Cartão
  quantidade: 2
  horario: "16:30"
  dias_semana: ["Segunda", "Quarta", "Sexta"]

- fluxo_name: Fluxo Cartão
  quantidade: 3
  horario: "16:32"
  dias_semana: ["Todos"]

- fluxo_name: "extracao_jira_sprint"
  horario: "13:24"
  dias_semana: ["Segunda","Terça","Quarta","Quinta","Sexta"]
  quantidade: 1
  servico: "jira"

- fluxo_name: "extracao_zephyr_diaria"
  horario: "13:25"
  dias_semana: ["Todos"]
  quantidade: 1
  servico: "zephyr"
