- fluxo_name: extracao_zephyr_diaria
  horario: '14:34'
  data: 26/09/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"zephyr","testcases":2,"executions":0,"saved":["config/data/zephyr_testcases_20250926_173343.csv","config/data/zephyr_executions_20250926_173343.csv"],"latest":["config/data/zephyr_testcases_latest.csv","config/data/zephyr_executions_latest.csv"]}'
  endpoint: /run_zephyr/
  api_url: http://127.0.0.1:8000
- fluxo_name: extracao_zephyr_diaria
  horario: '14:34'
  data: 02/10/2025
  status: Falha
  mensagem: '500 Server Error: Internal Server Error for url: http://127.0.0.1:8000/run_zephyr/'
  endpoint: /run_zephyr/
  api_url: http://127.0.0.1:8000
- fluxo_name: extracao_jira_sprint
  horario: '15:58'
  data: 02/10/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"jira","count":0,"saved":"config/data/jira_issues_20251002_155742.csv","latest":"config/data/jira_issues_latest.csv"}'
  endpoint: /run_jira/
  api_url: http://127.0.0.1:8000
- fluxo_name: extracao_jira_sprint
  horario: '15:58'
  data: 02/10/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"jira","count":0,"saved":"config/data/jira_issues_20251002_185745.csv","latest":"config/data/jira_issues_latest.csv"}'
  endpoint: /run_jira/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '16:32'
  data: 02/10/2025
  status: Sucesso
  mensagem: '{"status":"Sucesso","contexto":[{},{},{}]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: extracao_jira_sprint
  horario: '23:58'
  data: 02/10/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"jira","count":6,"saved":"config/database/temp/jira_issues_20251003_025724.csv","latest":"config/database/temp/jira_issues_latest.csv"}'
  endpoint: /run_jira/
  api_url: http://127.0.0.1:8000
- fluxo_name: extracao_zephyr_diaria
  horario: '23:59'
  data: 02/10/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"zephyr","projects":["KAN"],"testcases":4,"executions":0,"testcycles":0,"statuses":14,"saved":["config/database/temp/zephyr_testcases_20251003_025826.csv","config/database/temp/zephyr_testexecutions_20251003_025826.csv","config/database/temp/zephyr_testcycles_20251003_025826.csv","config/database/temp/zephyr_statuses_20251003_025826.csv"],"latest":["config/database/temp/zephyr_testcases_latest.csv","config/database/temp/zephyr_testexecutions_latest.csv","config/database/temp/zephyr_testcycles_latest.csv","config/database/temp/zephyr_statuses_latest.csv"],"concurrency":{"max_workers":12,"page_size":100,"pause_every":200,"pause_secs":0.2},"filters_used":{"tc_createdAfter":"2025-01-01","tc_createdBefore":null,"exec_actualEndAfter":"2025-01-01T00:00:00Z","exec_actualEndBefo'
  endpoint: /run_zephyr/
  api_url: http://127.0.0.1:8000
- fluxo_name: extracao_jira_sprint
  horario: '9:45'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"jira","count":6,"saved":"config/database/temp/jira_issues_20251003_124536.csv","latest":"config/database/temp/jira_issues_latest.csv"}'
  endpoint: /run_jira/
  api_url: http://127.0.0.1:8000
- fluxo_name: extracao_zephyr_diaria
  horario: '9:51'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"ok":true,"source":"zephyr","projects":["KAN"],"testcases":4,"executions":0,"testcycles":0,"statuses":14,"saved":["config/database/temp/zephyr_testcases_20251003_125039.csv","config/database/temp/zephyr_testexecutions_20251003_125039.csv","config/database/temp/zephyr_testcycles_20251003_125039.csv","config/database/temp/zephyr_statuses_20251003_125039.csv"],"latest":["config/database/temp/zephyr_testcases_latest.csv","config/database/temp/zephyr_testexecutions_latest.csv","config/database/temp/zephyr_testcycles_latest.csv","config/database/temp/zephyr_statuses_latest.csv"],"concurrency":{"max_workers":12,"page_size":100,"pause_every":200,"pause_secs":0.2},"filters_used":{"tc_createdAfter":"2025-01-01","tc_createdBefore":null,"exec_actualEndAfter":"2025-01-01T00:00:00Z","exec_actualEndBefo'
  endpoint: /run_zephyr/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '16:30'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"status":"Sucesso","contexto":[{},{}]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '16:32'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"status":"Sucesso","contexto":[{},{},{}]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:00'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"status":"Sucesso","contexto":[{},{}]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:00'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"status":"Sucesso","contexto":[{},{}]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:02'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"status":"Sucesso","contexto":[{},{},{}]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:02'
  data: 03/10/2025
  status: Sucesso
  mensagem: '{"status":"Sucesso","contexto":[{},{},{}]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:00'
  data: 07/11/2025
  status: Sucesso
  mensagem: '{"status":"Falha","erros":["Fluxo ''Fluxo Cartão'' não encontrado ou
    sem passos."]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:00'
  data: 07/11/2025
  status: Falha
  mensagem: 'HTTPConnectionPool(host=''127.0.0.1'', port=8000): Max retries exceeded
    with url: /run_fluxo/ (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection
    object at 0x7f439fc60fd0>: Failed to establish a new connection: [Errno 111] Connection
    refused''))'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:02'
  data: 07/11/2025
  status: Sucesso
  mensagem: '{"status":"Falha","erros":["Fluxo ''Fluxo Cartão'' não encontrado ou
    sem passos."]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:00'
  data: 12/11/2025
  status: Sucesso
  mensagem: '{"status":"Falha","erros":["Fluxo ''Fluxo Cartão'' não encontrado ou
    sem passos."]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
- fluxo_name: Fluxo Cartão
  horario: '14:02'
  data: 12/11/2025
  status: Sucesso
  mensagem: '{"status":"Falha","erros":["Fluxo ''Fluxo Cartão'' não encontrado ou
    sem passos."]}'
  endpoint: /run_fluxo/
  api_url: http://127.0.0.1:8000
