- fluxo_name: Fluxo Cartão
  quantidade: 2
  horario: "14:00"
  dias_semana: ["Segunda", "Quarta", "Sexta"]

- fluxo_name: Fluxo Cartão
  quantidade: 3
  horario: "14:02"
  dias_semana: ["Todos"]