- dados:
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    status: Sucesso
  data_criacao: 10/10/2025 11:55:43
  fluxo_name: Consultar Todo Externo
  status: valida
- dados:
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    status: Sucesso
  data_criacao: 10/10/2025 14:22:59
  fluxo_name: Consultar Todo Externo
  status: valida
- dados:
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        url: https://jsonplaceholder.typicode.com/todos/1
    status: Sucesso
  data_criacao: 10/10/2025 14:43:54
  fluxo_name: Consultar Todo Externo
  status: valida
- dados:
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    - https://jsonplaceholder.typicode.com/todos/1:
        method: GET
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
        step: https://jsonplaceholder.typicode.com/todos/1
        url: https://jsonplaceholder.typicode.com/todos/1
    status: Sucesso
  data_criacao: 10/10/2025 20:24:43
  fluxo_name: Consultar Todo Externo
  status: valida
- fluxo_name: Consultar Todo Externo
  status: valida
  dados:
    status: Sucesso
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
    - https://jsonplaceholder.typicode.com/todos/1:
        step: https://jsonplaceholder.typicode.com/todos/1
        method: GET
        url: https://jsonplaceholder.typicode.com/todos/1
        status_code: 200
        response:
          userId: 1
          id: 1
          title: delectus aut autem
          completed: false
  data_criacao: 10/10/2025 20:40:58
