- dados:
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    status: Sucesso
  data_criacao: 07/10/2025 11:11:23
  fluxo_name: Consultar Todo Externo
  status: valida
- dados:
    contexto:
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    - onboarding:
        error: '404 Client Error: Not Found for url: http://127.0.0.1:8000/%7B''url'':%20''http://localhost:8080/onboarding'',%20''method'':%20''POST''%7D'
        status_code: null
    status: Sucesso
  data_criacao: 07/10/2025 11:18:17
  fluxo_name: Onboarding de Cartão
  status: valida
- dados:
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    status: Sucesso
  data_criacao: 07/10/2025 16:34:19
  fluxo_name: Consultar Todo Externo
  status: valida
- dados:
    contexto:
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    - https://jsonplaceholder.typicode.com/todos/1:
        response:
          completed: false
          id: 1
          title: delectus aut autem
          userId: 1
        status_code: 200
    status: Sucesso
  data_criacao: 08/10/2025 11:24:51
  fluxo_name: Consultar Todo Externo
  status: valida
