FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY apps/app/ app/
COPY apps/agent/ apps/agent/
COPY config/ config/
COPY src/extractor/ extractor/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

ENV PYTHONHTTPSVERIFY=0