[jira]
base_url = "https://suaempresa.atlassian.net"
email    = "voce@empresa.com"
api_token = "JIRA_API_TOKEN"

[zephyr]
base_url = "https://api.zephyrscale.smartbear.com/v2"  # Zephyr Scale Cloud
api_token = "ZEPHYR_SCALE_TOKEN"

[app]
default_project = "PROJ"
timezone = "America/Sao_Paulo"
