[jira]
base_url = "https://bruno-luiz-cassiano-dos-santos.atlassian.net"
email    = "bruno15l@hotmail.com"
api_token = "ATATT3xFfGF0d9sjvVP6ZEMU6uUJzIm9TXlI9cAZXac9VLYk_CV9M6tw7E7rkNOuB924LvbSvsm2vMplL8_RPHB-E2HhkFXF7iwZOMYnPx5WheshHVck3oskpecZ90UIRVbiQ45QXEhClxBmz_hQ8a6i4Fwh6FB56IGhFd7EC-mcAlfhb5tb7p8=ABA8D088"

[zephyr]
base_url = "https://api.zephyrscale.smartbear.com/v2"  # Zephyr Scale Cloud
api_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczovL2JydW5vLWx1aXotY2Fzc2lhbm8tZG9zLXNhbnRvcy5hdGxhc3NpYW4ubmV0IiwidXNlciI6eyJhY2NvdW50SWQiOiI1YjgwNTZmYWI1N2VkMjU5MzNmNjRlOTQiLCJ0b2tlbklkIjoiZTNiMGQ4OWEtMmM2Zi00YmZkLTljZGQtZGMzYWU0YTA5ZTg2In19LCJpc3MiOiJjb20ua2Fub2FoLnRlc3QtbWFuYWdlciIsInN1YiI6IjRkMzhkNmU0LWI3NTYtM2U1Yi05NDJiLTc5Njg3MzU0MTNmMyIsImV4cCI6MTc4ODMwNDg1NSwiaWF0IjoxNzU2NzY4ODU1fQ.O-0P-ynmpDYrPf0KGN1IB_KTnbRljTYmlOC9qgO5djw"

[app]
default_project = "PROJ"
timezone = "America/Sao_Paulo"
